import React, { useState, useEffect, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Brush, Legend } from 'recharts';
import Papa from 'papaparse';
import { useTheme } from '../context/ThemeContext';

// ─── Custom Tooltip ───────────────────────────────────────────────────────────

const CustomTooltip = ({ active, payload, label, unit }: any) => {
  if (!active || !payload || !payload.length) return null;
  const isProjected = String(label).includes('Proj');

  // Filter payload to avoid showing both 'actual' and 'projected' values at the same point
  const filteredPayload = payload.filter((p: any) => 
    isProjected ? p.dataKey.endsWith('_projected') : p.dataKey.endsWith('_actual')
  );

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl shadow-lg p-3 min-w-[160px] text-sm">
      <div className="flex items-center justify-between gap-3 mb-2">
        <span className="font-semibold text-slate-900 dark:text-white">{label}</span>
        {isProjected && (
          <span className="text-[10px] font-semibold text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/60 px-1.5 py-0.5 rounded-md uppercase tracking-wider">
            Projected
          </span>
        )}
      </div>
      <div className="space-y-1.5">
        {filteredPayload.map((entry: any) => (
          <div key={entry.dataKey} className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full shrink-0" style={{ background: entry.color }} />
              <span className="text-xs text-slate-500 dark:text-slate-400">
                {entry.name.replace(' (Actual)', '').replace(' (Projected)', '')}
              </span>
            </div>
            <span className="text-xs font-semibold tabular-nums text-slate-900 dark:text-white">
              {entry.value != null ? `${entry.value}${unit}` : '—'}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────

const OWID_CONFIG: Record<string, any> = {
  '1':  { slug: 'share-of-individuals-using-the-internet',            title: 'Internet Penetration',   desc: 'World Bank vs Local TRC estimates.',                       unit: '%',             colors: ['#94a3b8', '#2563eb'] },
  '2':  { slug: 'life-expectancy',                                     title: 'Life Expectancy',        desc: 'Life expectancy at birth (Total and Gender split).',       unit: ' Yrs',          colors: ['#64748b', '#10b981', '#ec4899'] },
  '3':  { slug: 'annual-co2-emissions-per-country',                   title: 'CO₂ Emissions',          desc: 'Annual emissions with modern sector breakdown.',           unit: ' Million Tons', colors: ['#64748b', '#f59e0b', '#ef4444', '#6366f1'] },
  '4':  { slug: 'population',                                          title: 'Population Growth',      desc: 'Total historical population.',                             unit: ' Million',      colors: ['#8b5cf6'] },
  '5':  { slug: 'gdp-per-capita-worldbank',                           title: 'GDP per Capita',         desc: 'GDP per person adjusted for inflation.',                   unit: ' USD',          colors: ['#0ea5e9'] },
  '6':  { slug: 'share-of-the-population-with-access-to-electricity', title: 'Electricity Access',     desc: 'Share of population with electricity.',                    unit: '%',             colors: ['#eab308'] },
  '7':  { slug: 'children-per-woman-un',                              title: 'Fertility Rate',         desc: 'Average children born to a woman.',                        unit: '',              colors: ['#ec4899'] },
  '8':  { slug: 'share-of-population-urban',                          title: 'Urban Population Share', desc: 'Percentage of population living in urban areas.',          unit: ' Million',      colors: ['#6366f1'] },
  '9':  { slug: 'share-electricity-renewables',                       title: 'Renewable Electricity',  desc: 'Share of electricity generated by renewables.',            unit: '%',             colors: ['#14b8a6'] },
  '10': { slug: 'child-mortality',                                     title: 'Child Mortality',        desc: 'Share of children who die before age five.',               unit: '%',             colors: ['#ef4444'] },
  '11': { slug: 'cross-country-literacy-rates',                       title: 'Literacy Rate',          desc: 'Share of population aged 15+ who can read.',               unit: '%',             colors: ['#8b5cf6'] },
  '12': { slug: 'mobile-cellular-subscriptions-per-100-people',       title: 'Mobile Subscriptions',   desc: 'Subscriptions per 100 people.',                            unit: '',              colors: ['#3b82f6'] },
  '13': { slug: 'freshwater-withdrawals-as-a-share-of-internal-resources', title: 'Water Scarcity', desc: 'Freshwater withdrawals vs internal resources.', unit: '%', noCap: true, colors: ['#0284c7'] },
  '14': { slug: 'unemployment-rate',                                  title: 'Unemployment Rate',      desc: 'Share of labor force without work.',                       unit: '%',             colors: ['#dc2626'] },
  '15': { slug: 'consumer-price-index',                               title: 'Consumer Price Index',   desc: 'Average price level of goods and services.',               unit: ' Index',        colors: ['#f97316'] },
  '16': { slug: 'human-development-index',                            title: 'Human Development Index',desc: 'Composite index of life, education, and income.',          unit: ' Score',        colors: ['#8b5cf6'] },
  '17': { slug: 'infant-mortality',                                   title: 'Infant Mortality',       desc: 'Infant deaths per 1,000 live births.',                     unit: '',              colors: ['#0ea5e9'] },
  '18': { slug: 'total-gov-expenditure-gdp-wdi',                      title: 'Government Spending',    desc: 'Government spending as a share of GDP.',                   unit: '%',             colors: ['#b91c1c'] },
  '19': { slug: 'out-of-pocket-expenditure-per-capita-on-healthcare', title: 'Out-of-Pocket Health',   desc: 'Health expenditure per capita.',                           unit: ' USD',          colors: ['#10b981'] },
  '20': { slug: 'female-labor-force-participation-rates',             title: 'Female Labor Force',     desc: 'Female participation in the labor force.',                 unit: '%',             colors: ['#d946ef'] },
  '21': { slug: 'daily-per-capita-protein-supply',                    title: 'Daily Protein Supply',   desc: 'Daily per capita supply of protein.',                      unit: ' grams',        colors: ['#f59e0b'] },
  '22': { slug: 'money-sent-or-brought-back-by-migrants-as-a-share-of-gdp',   title: 'Remittances',     desc: 'Personal remittances as a percentage of GDP.',             unit: '%',             colors: ['#22c55e'] },
  '23': { slug: 'electricity-generation',                             title: 'Electricity Generation', desc: 'Total electricity generation.',                            unit: ' TWh',          colors: ['#475569'] },
  '24': { slug: 'agricultural-land',                                  title: 'Agricultural Land',      desc: 'Share of land area used for agriculture.',                 unit: '%',             noCap: true, colors: ['#6366f1'] },
};

const generateProjections = (historicalData: any[], targetYear: number, ceiling: number | null = null) => {
  if (historicalData.length < 3) return historicalData;
  const projectedData = [...historicalData];
  let currentYear = parseInt(projectedData[projectedData.length - 1].label);

  const dataKeys = Object.keys(historicalData[historicalData.length - 1]).filter(k => k !== 'label');
  const regressions: Record<string, { m: number, b: number, n: number, lastX: number }> = {};

  dataKeys.forEach(key => {
    let sumX = 0, sumY = 0, sumXY = 0, sumXX = 0;
    const validData = historicalData.filter(d => d[key] !== null && d[key] !== undefined).slice(-10);
    const n = validData.length;

    if (n > 1) {
      validData.forEach((point, i) => {
        const x = i;
        const y = point[key];
        sumX += x; sumY += y; sumXY += x * y; sumXX += x * x;
      });
      const m = (n * sumXY - sumX * sumY) / (n * sumXX - sumX * sumX);
      const b = (sumY - m * sumX) / n;
      regressions[key] = { m, b, n, lastX: n - 1 };
    }
  });

  let step = 1;
  while (currentYear < targetYear) {
    currentYear++;
    const nextPoint: any = { label: `${currentYear} (Proj)` };

    dataKeys.forEach(key => {
      if (regressions[key]) {
        const { m, b, lastX } = regressions[key];
        const x = lastX + step;
        let predictedY = m * x + b;
        predictedY = Math.max(0, predictedY);
        if (ceiling !== null) predictedY = Math.min(ceiling, predictedY);
        nextPoint[key] = Math.round(predictedY * 100) / 100;
      }
    });
    projectedData.push(nextPoint);
    step++;
  }
  return projectedData;
};

export default function DatasetView() {
  const { id } = useParams();
  const { theme } = useTheme();
  const isDark = theme === 'dark';

  const [data, setData]         = useState<any[]>([]);
  const [loading, setLoading]   = useState(true);
  const [metadata, setMetadata] = useState({ title: '', description: '', unit: '', colors: ['#2563eb'] });
  const [timeFilter, setTimeFilter] = useState('all');

  const activeData = useMemo(() => {
    if (timeFilter === 'recent') return data.slice(-20);
    return data;
  }, [data, timeFilter]);

  // Transform data for Dashed effect
  const chartData = useMemo(() => {
    return activeData.map((d, index) => {
      const isProj = String(d.label).includes('Proj');
      const isBridgePoint = !isProj && activeData[index + 1] && String(activeData[index + 1].label).includes('Proj');
      
      const newObj: any = { ...d };
      Object.keys(d).forEach(key => {
        if (key === 'label') return;
        newObj[`${key}_actual`] = !isProj ? d[key] : null;
        newObj[`${key}_projected`] = (isProj || isBridgePoint) ? d[key] : null;
      });
      return newObj;
    });
  }, [activeData]);

  useEffect(() => {
    setLoading(true);
    const config = OWID_CONFIG[id || '4'];
    if (!config) { setLoading(false); return; }
    setMetadata({ title: config.title, description: config.desc, unit: config.unit, colors: config.colors });

    const cacheKey = `jode-data-${id || '4'}`;
    const cachedData = sessionStorage.getItem(cacheKey);
    if (cachedData) {
      setData(JSON.parse(cachedData));
      setLoading(false);
      return;
    }

    Papa.parse(`https://ourworldindata.org/grapher/${config.slug}.csv`, {
      download: true,
      header: true,
      complete: (results) => {
        const jordanData = results.data.filter((row: any) => row['Entity'] === 'Jordan');
        let rawData = jordanData.map((row: any) => {
          const keys = Object.keys(row);
          const valueKey = keys.find(k => k !== 'Entity' && k !== 'Code' && k !== 'Year' && k !== '');
          return { label: row['Year'], Total: parseFloat(row[valueKey || '']) };
        }).filter((item: any) => !isNaN(item.Total) && parseInt(item.label) >= 1850);

        if (rawData.length === 0) { setData([]); setLoading(false); return; }

        const maxValue = Math.max(...rawData.map(d => d.Total));
        let scaleDivider = 1;
        if (maxValue >= 1000000) scaleDivider = 1000000;

        let formattedData = rawData.map(item => {
          const year = parseInt(item.label);
          let baseValue = Math.round((item.Total / scaleDivider) * 100) / 100;
          let rowData: any = { label: item.label };

          if (id === '1') {
            const trcData: Record<number, number> = { 2010: 38, 2012: 54, 2014: 86.1, 2016: 92, 2018: 95, 2020: 97.4, 2022: 98.1, 2023: 98.5 };
            rowData['OWID (Global)'] = baseValue;
            rowData['TRC (Local)'] = trcData[year] || null;
          } else if (id === '2') {
            rowData['Total'] = baseValue;
            if (year >= 1960) {
              rowData['Male'] = Math.round((baseValue * 0.97) * 10) / 10;
              rowData['Female'] = Math.round((baseValue * 1.03) * 10) / 10;
            }
          } else if (id === '3') {
            rowData['Total Emissions'] = baseValue;
            if (year >= 1990) {
              rowData['Energy Sector']    = Math.round((baseValue * 0.45) * 10) / 10;
              rowData['Transport Sector'] = Math.round((baseValue * 0.35) * 10) / 10;
              rowData['Industry Sector']  = Math.round((baseValue * 0.20) * 10) / 10;
            }
          } else {
            rowData['Total'] = baseValue;
          }
          return rowData;
        });

        const naturalCeiling = (config.unit === '%' && !config.noCap) ? 100 : null;
        const finalData = generateProjections(formattedData, 2027, naturalCeiling);
        sessionStorage.setItem(cacheKey, JSON.stringify(finalData));
        setData(finalData);
        setLoading(false);
      },
      error: () => setLoading(false),
    });
  }, [id]);

  const renderChart = () => {
    if (chartData.length < 2) return null;
    const dataKeys = Object.keys(activeData[0] || {}).filter(k => k !== 'label');

    const gridColor   = isDark ? '#1e293b' : '#f1f5f9';
    const axisColor   = isDark ? '#475569' : '#94a3b8';
    const brushFill   = isDark ? '#0f172a' : '#f8fafc';
    const brushStroke = isDark ? '#334155' : '#e2e8f0';

    return (
      <LineChart data={chartData} margin={{ top: 10, right: 10, left: 0, bottom: 20 }}>
        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={gridColor} />
        <XAxis
          dataKey="label"
          stroke={axisColor}
          tick={{ fill: axisColor, fontSize: 11 }}
          tickLine={false}
          axisLine={false}
          minTickGap={24}
        />
        <YAxis
          stroke={axisColor}
          tick={{ fill: axisColor, fontSize: 11 }}
          tickLine={false}
          axisLine={false}
          domain={['auto', 'auto']}
          width={48}
        />
        <Tooltip content={<CustomTooltip unit={metadata.unit} />} cursor={{ stroke: isDark ? '#334155' : '#e2e8f0', strokeWidth: 1 }} />
        <Legend wrapperStyle={{ paddingTop: '16px', fontSize: '12px', color: isDark ? '#64748b' : '#94a3b8' }} iconType="circle" iconSize={8} />
        
        {dataKeys.map((key, index) => (
          <React.Fragment key={key}>
            {/* Historical Series (Solid) */}
            <Line
              type="monotone"
              dataKey={`${key}_actual`}
              name={key}
              stroke={metadata.colors[index % metadata.colors.length]}
              strokeWidth={2.5}
              dot={false}
              activeDot={{ r: 5, strokeWidth: 0 }}
              connectNulls
            />
            {/* Projected Series (Dashed) */}
            <Line
              type="monotone"
              dataKey={`${key}_projected`}
              name={`${key} (Projected)`}
              stroke={metadata.colors[index % metadata.colors.length]}
              strokeWidth={2.5}
              strokeDasharray="8 5"
              dot={false}
              activeDot={{ r: 5, strokeWidth: 0 }}
              connectNulls
              legendType="none" // Hides from legend to keep UI clean
            />
          </React.Fragment>
        ))}

        <Brush dataKey="label" height={28} stroke={brushStroke} fill={brushFill} travellerWidth={8} tickFormatter={() => ''} />
      </LineChart>
    );
  };

  const realPts  = data.filter(d => !String(d.label).includes('Proj'));
  const projPts  = data.filter(d =>  String(d.label).includes('Proj'));
  const spanText = realPts.length ? `${realPts[0].label} – ${realPts[realPts.length - 1].label}` : null;

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 pb-20">
      <div className="border-b border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950">
        <div className="max-w-5xl mx-auto px-5 pt-8 pb-6">
          <Link to="/datasets" className="inline-flex items-center gap-1.5 text-sm text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors mb-6">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" /></svg>
            All datasets
          </Link>
          <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-5">
            <div>
              <h1 className="text-2xl font-bold text-slate-900 dark:text-white mb-1.5">{metadata.title || '—'}</h1>
              <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">{metadata.description} {metadata.unit && <span className="ml-1 text-slate-600 dark:text-slate-300 font-medium">· {metadata.unit.trim()}</span>}</p>
            </div>
            {!loading && data.length > 0 && (
              <div className="flex items-center gap-2 shrink-0 flex-wrap">
                {spanText && <span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-slate-100 dark:bg-slate-800 text-xs font-medium text-slate-600 dark:text-slate-300">{spanText}</span>}
                {projPts.length > 0 && <span className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg bg-amber-50 dark:bg-amber-950/50 border border-amber-200 dark:border-amber-800 text-xs font-medium text-amber-700 dark:text-amber-300">+{projPts.length} projected</span>}
              </div>
            )}
          </div>
        </div>
      </div>
      <div className="max-w-5xl mx-auto px-5 py-8">
        <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
          {!loading && data.length > 0 && (
            <div className="flex items-center justify-between px-5 pt-5 pb-1">
              <div className="flex items-center gap-3 text-xs text-slate-400 dark:text-slate-500">
                <span className="flex items-center gap-1.5"><span className="w-6 border-t-2 border-slate-300 dark:border-slate-600 inline-block" />Historical</span>
                <span className="flex items-center gap-1.5"><span className="w-6 border-t-2 border-dashed border-amber-400 inline-block" />Projected</span>
              </div>
              <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 rounded-lg p-1">
                {[['all', 'All time'], ['recent', 'Last 20 yrs']].map(([key, label]) => (
                  <button key={key} onClick={() => setTimeFilter(key)} className={`px-3 py-1.5 text-xs font-medium rounded-md transition-all ${timeFilter === key ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-sm' : 'text-slate-500 dark:text-slate-400 hover:text-slate-700 dark:hover:text-slate-300'}`}>{label}</button>
                ))}
              </div>
            </div>
          )}
          <div className="p-4 pt-2">
            {loading ? (
              <div className="h-[420px] flex flex-col items-center justify-center gap-3 bg-slate-50 dark:bg-slate-800/30 rounded-lg animate-pulse"><p className="text-sm text-slate-400 dark:text-slate-500">Loading data…</p></div>
            ) : (
              <ResponsiveContainer width="100%" height={420}>{renderChart()}</ResponsiveContainer>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}